name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run Ruff on changed lines
        run: |
          git fetch origin main:main
          ruff check . | ondivi --baseline main --only-violations